//<auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AccountabilityInformationSystem.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class AddMeasurementPointData : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Product_ApCodes_ApCodeId",
                schema: "ais",
                table: "Product");

            migrationBuilder.DropForeignKey(
                name: "FK_Product_BrandNames_BrandNameId",
                schema: "ais",
                table: "Product");

            migrationBuilder.DropForeignKey(
                name: "FK_Product_CnCodes_CnCodeId",
                schema: "ais",
                table: "Product");

            migrationBuilder.DropForeignKey(
                name: "FK_Product_ProductType_ProductTypeId",
                schema: "ais",
                table: "Product");

            migrationBuilder.DropPrimaryKey(
                name: "PK_ProductType",
                schema: "ais",
                table: "ProductType");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Product",
                schema: "ais",
                table: "Product");

            migrationBuilder.RenameTable(
                name: "ProductType",
                schema: "ais",
                newName: "ProductTypes",
                newSchema: "ais");

            migrationBuilder.RenameTable(
                name: "Product",
                schema: "ais",
                newName: "Products",
                newSchema: "ais");

            migrationBuilder.RenameIndex(
                name: "IX_Product_ProductTypeId",
                schema: "ais",
                table: "Products",
                newName: "IX_Products_ProductTypeId");

            migrationBuilder.RenameIndex(
                name: "IX_Product_Code",
                schema: "ais",
                table: "Products",
                newName: "IX_Products_Code");

            migrationBuilder.RenameIndex(
                name: "IX_Product_CnCodeId",
                schema: "ais",
                table: "Products",
                newName: "IX_Products_CnCodeId");

            migrationBuilder.RenameIndex(
                name: "IX_Product_BrandNameId",
                schema: "ais",
                table: "Products",
                newName: "IX_Products_BrandNameId");

            migrationBuilder.RenameIndex(
                name: "IX_Product_ApCodeId",
                schema: "ais",
                table: "Products",
                newName: "IX_Products_ApCodeId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_ProductTypes",
                schema: "ais",
                table: "ProductTypes",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Products",
                schema: "ais",
                table: "Products",
                column: "Id");

            migrationBuilder.CreateTable(
                name: "MeasurementPointData",
                schema: "flow",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    MeasurementPointId = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Number = table.Column<int>(type: "int", maxLength: 50, nullable: false),
                    BeginTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    EndTime = table.Column<DateTime>(type: "datetime2", nullable: false),
                    FlowDirectionType = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    ProductId = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    TotalizerBeginGrossObservableVolume = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    TotalizerEndGrossObservableVolume = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    TotalizerBeginGrossStandardVolume = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    TotalizerEndGrossStandardVolume = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    TotalizerBeginMass = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    TotalizerEndMass = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    GrossObservableVolume = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    GrossStandardVolume = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    Mass = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    AverageObservableDensity = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    AverageReferenceDensity = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    AverageTemperature = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    AlcoholContent = table.Column<decimal>(type: "decimal(18,3)", precision: 18, scale: 3, nullable: true),
                    BatchNumber = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    ExternalId = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    CreatedBy = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    ModifiedAt = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MeasurementPointData", x => x.Id);
                    table.ForeignKey(
                        name: "FK_MeasurementPointData_MeasurementPoints_MeasurementPointId",
                        column: x => x.MeasurementPointId,
                        principalSchema: "flow",
                        principalTable: "MeasurementPoints",
                        principalColumn: "Id");
                    table.ForeignKey(
                        name: "FK_MeasurementPointData_Products_ProductId",
                        column: x => x.ProductId,
                        principalSchema: "ais",
                        principalTable: "Products",
                        principalColumn: "Id");
                });

            migrationBuilder.CreateIndex(
                name: "IX_MeasurementPointData_BeginTime",
                schema: "flow",
                table: "MeasurementPointData",
                column: "BeginTime");

            migrationBuilder.CreateIndex(
                name: "IX_MeasurementPointData_EndTime",
                schema: "flow",
                table: "MeasurementPointData",
                column: "EndTime");

            migrationBuilder.CreateIndex(
                name: "IX_MeasurementPointData_FlowDirectionType",
                schema: "flow",
                table: "MeasurementPointData",
                column: "FlowDirectionType");

            migrationBuilder.CreateIndex(
                name: "IX_MeasurementPointData_MeasurementPointId",
                schema: "flow",
                table: "MeasurementPointData",
                column: "MeasurementPointId");

            migrationBuilder.CreateIndex(
                name: "IX_MeasurementPointData_MeasurementPointId_FlowDirectionType_Number_BeginTime_EndTime",
                schema: "flow",
                table: "MeasurementPointData",
                columns: ["MeasurementPointId", "Number", "BeginTime", "EndTime", "FlowDirectionType"],
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_MeasurementPointData_Number",
                schema: "flow",
                table: "MeasurementPointData",
                column: "Number");

            migrationBuilder.CreateIndex(
                name: "IX_MeasurementPointData_ProductId",
                schema: "flow",
                table: "MeasurementPointData",
                column: "ProductId");

            migrationBuilder.AddForeignKey(
                name: "FK_Products_ApCodes_ApCodeId",
                schema: "ais",
                table: "Products",
                column: "ApCodeId",
                principalSchema: "excise",
                principalTable: "ApCodes",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Products_BrandNames_BrandNameId",
                schema: "ais",
                table: "Products",
                column: "BrandNameId",
                principalSchema: "excise",
                principalTable: "BrandNames",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Products_CnCodes_CnCodeId",
                schema: "ais",
                table: "Products",
                column: "CnCodeId",
                principalSchema: "excise",
                principalTable: "CnCodes",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Products_ProductTypes_ProductTypeId",
                schema: "ais",
                table: "Products",
                column: "ProductTypeId",
                principalSchema: "ais",
                principalTable: "ProductTypes",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Products_ApCodes_ApCodeId",
                schema: "ais",
                table: "Products");

            migrationBuilder.DropForeignKey(
                name: "FK_Products_BrandNames_BrandNameId",
                schema: "ais",
                table: "Products");

            migrationBuilder.DropForeignKey(
                name: "FK_Products_CnCodes_CnCodeId",
                schema: "ais",
                table: "Products");

            migrationBuilder.DropForeignKey(
                name: "FK_Products_ProductTypes_ProductTypeId",
                schema: "ais",
                table: "Products");

            migrationBuilder.DropTable(
                name: "MeasurementPointData",
                schema: "flow");

            migrationBuilder.DropPrimaryKey(
                name: "PK_ProductTypes",
                schema: "ais",
                table: "ProductTypes");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Products",
                schema: "ais",
                table: "Products");

            migrationBuilder.RenameTable(
                name: "ProductTypes",
                schema: "ais",
                newName: "ProductType",
                newSchema: "ais");

            migrationBuilder.RenameTable(
                name: "Products",
                schema: "ais",
                newName: "Product",
                newSchema: "ais");

            migrationBuilder.RenameIndex(
                name: "IX_Products_ProductTypeId",
                schema: "ais",
                table: "Product",
                newName: "IX_Product_ProductTypeId");

            migrationBuilder.RenameIndex(
                name: "IX_Products_Code",
                schema: "ais",
                table: "Product",
                newName: "IX_Product_Code");

            migrationBuilder.RenameIndex(
                name: "IX_Products_CnCodeId",
                schema: "ais",
                table: "Product",
                newName: "IX_Product_CnCodeId");

            migrationBuilder.RenameIndex(
                name: "IX_Products_BrandNameId",
                schema: "ais",
                table: "Product",
                newName: "IX_Product_BrandNameId");

            migrationBuilder.RenameIndex(
                name: "IX_Products_ApCodeId",
                schema: "ais",
                table: "Product",
                newName: "IX_Product_ApCodeId");

            migrationBuilder.AddPrimaryKey(
                name: "PK_ProductType",
                schema: "ais",
                table: "ProductType",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Product",
                schema: "ais",
                table: "Product",
                column: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Product_ApCodes_ApCodeId",
                schema: "ais",
                table: "Product",
                column: "ApCodeId",
                principalSchema: "excise",
                principalTable: "ApCodes",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Product_BrandNames_BrandNameId",
                schema: "ais",
                table: "Product",
                column: "BrandNameId",
                principalSchema: "excise",
                principalTable: "BrandNames",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Product_CnCodes_CnCodeId",
                schema: "ais",
                table: "Product",
                column: "CnCodeId",
                principalSchema: "excise",
                principalTable: "CnCodes",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_Product_ProductType_ProductTypeId",
                schema: "ais",
                table: "Product",
                column: "ProductTypeId",
                principalSchema: "ais",
                principalTable: "ProductType",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
