//<auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AccountabilityInformationSystem.Api.Migrations.Application
{
    /// <inheritdoc />
    public partial class AddUser : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "ais",
                table: "Warehouses");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "ais",
                table: "Warehouses");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "ais",
                table: "Warehouses");

            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "flow",
                table: "MeasurementPoints");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "flow",
                table: "MeasurementPoints");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "flow",
                table: "MeasurementPoints");

            migrationBuilder.DropColumn(
                name: "DeletedAt",
                schema: "flow",
                table: "Ikunks");

            migrationBuilder.DropColumn(
                name: "DeletedBy",
                schema: "flow",
                table: "Ikunks");

            migrationBuilder.DropColumn(
                name: "IsDeleted",
                schema: "flow",
                table: "Ikunks");

            migrationBuilder.CreateTable(
                name: "Users",
                schema: "ais",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    Email = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    FirstName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    MiddleName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: true),
                    LastName = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false),
                    Image = table.Column<string>(type: "nvarchar(2048)", maxLength: 2048, nullable: true),
                    IdentityId = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(128)", maxLength: 128, nullable: true),
                    ModifiedAt = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Users", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Users_Email",
                schema: "ais",
                table: "Users",
                column: "Email",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Users_IdentityId",
                schema: "ais",
                table: "Users",
                column: "IdentityId",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Users",
                schema: "ais");

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "ais",
                table: "Warehouses",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "ais",
                table: "Warehouses",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "ais",
                table: "Warehouses",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "flow",
                table: "MeasurementPoints",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "flow",
                table: "MeasurementPoints",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "flow",
                table: "MeasurementPoints",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "DeletedAt",
                schema: "flow",
                table: "Ikunks",
                type: "datetime2",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "DeletedBy",
                schema: "flow",
                table: "Ikunks",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsDeleted",
                schema: "flow",
                table: "Ikunks",
                type: "bit",
                nullable: false,
                defaultValue: false);
        }
    }
}
