// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AccountabilityInformationSystem.Api.Infrastructure.Migrations.Application
{
    /// <inheritdoc />
    public partial class RefactorExciseNomenclature : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "BgDescription",
                schema: "excise",
                table: "CnCodes",
                newName: "DescriptionBg");

            migrationBuilder.RenameColumn(
                name: "BgDescription",
                schema: "excise",
                table: "BrandNames",
                newName: "DescriptionBg");

            migrationBuilder.RenameColumn(
                name: "BgDescription",
                schema: "excise",
                table: "ApCodes",
                newName: "DescriptionBg");

            migrationBuilder.AlterColumn<string>(
                name: "DescriptionEn",
                schema: "excise",
                table: "CnCodes",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "DescriptionEn",
                schema: "excise",
                table: "BrandNames",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "DescriptionEn",
                schema: "excise",
                table: "ApCodes",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000,
                oldNullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "DescriptionBg",
                schema: "excise",
                table: "CnCodes",
                newName: "BgDescription");

            migrationBuilder.RenameColumn(
                name: "DescriptionBg",
                schema: "excise",
                table: "BrandNames",
                newName: "BgDescription");

            migrationBuilder.RenameColumn(
                name: "DescriptionBg",
                schema: "excise",
                table: "ApCodes",
                newName: "BgDescription");

            migrationBuilder.AlterColumn<string>(
                name: "DescriptionEn",
                schema: "excise",
                table: "CnCodes",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000);

            migrationBuilder.AlterColumn<string>(
                name: "DescriptionEn",
                schema: "excise",
                table: "BrandNames",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000);

            migrationBuilder.AlterColumn<string>(
                name: "DescriptionEn",
                schema: "excise",
                table: "ApCodes",
                type: "nvarchar(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(1000)",
                oldMaxLength: 1000);
        }
    }
}
