//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AccountabilityInformationSystem.Api.Infrastructure.Migrations.Application
{
    /// <inheritdoc />
    public partial class UpdateUserWith2Fa : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "Enable2Fa",
                schema: "ais",
                table: "Users",
                type: "bit",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "SecretKey2Fa",
                schema: "ais",
                table: "Users",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Username",
                schema: "ais",
                table: "Users",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: false,
                defaultValue: "");

            migrationBuilder.Sql("UPDATE ais.Users SET Username = Email WHERE Username = '' OR Username IS NULL");

            migrationBuilder.AlterColumn<string>(
                name: "Username",
                schema: "ais",
                table: "Users",
                type: "nvarchar(128)",
                maxLength: 128,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "nvarchar(128)",
                oldMaxLength: 128,
                oldNullable: false,
                oldDefaultValue: "");

            migrationBuilder.CreateIndex(
                name: "IX_Users_Username",
                schema: "ais",
                table: "Users",
                column: "Username",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Users_Username",
                schema: "ais",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "Enable2Fa",
                schema: "ais",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "SecretKey2Fa",
                schema: "ais",
                table: "Users");

            migrationBuilder.DropColumn(
                name: "Username",
                schema: "ais",
                table: "Users");
        }
    }
}
