// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AccountabilityInformationSystem.Api.Infrastructure.Migrations.Application
{
    /// <inheritdoc />
    public partial class AddStorageFiles : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "BackImage",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.DropColumn(
                name: "FrontImage",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.DropColumn(
                name: "Receipt",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.AddColumn<string>(
                name: "BackImageId",
                schema: "family",
                table: "WarrantyRecords",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "FrontImageId",
                schema: "family",
                table: "WarrantyRecords",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "ReceiptId",
                schema: "family",
                table: "WarrantyRecords",
                type: "nvarchar(50)",
                maxLength: 50,
                nullable: true);

            migrationBuilder.CreateTable(
                name: "StorageFiles",
                schema: "ais",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    BlobName = table.Column<string>(type: "nvarchar(256)", maxLength: 256, nullable: false),
                    IsPrivate = table.Column<bool>(type: "bit", nullable: false),
                    OriginalFileName = table.Column<string>(type: "nvarchar(1024)", maxLength: 1024, nullable: false),
                    ContentType = table.Column<string>(type: "nvarchar(265)", maxLength: 265, nullable: false),
                    SizeBytes = table.Column<long>(type: "bigint", nullable: false),
                    CreatedBy = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ModifiedBy = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ModifiedAt = table.Column<DateTime>(type: "datetime2", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StorageFiles", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_WarrantyRecords_BackImageId",
                schema: "family",
                table: "WarrantyRecords",
                column: "BackImageId");

            migrationBuilder.CreateIndex(
                name: "IX_WarrantyRecords_FrontImageId",
                schema: "family",
                table: "WarrantyRecords",
                column: "FrontImageId");

            migrationBuilder.CreateIndex(
                name: "IX_WarrantyRecords_ReceiptId",
                schema: "family",
                table: "WarrantyRecords",
                column: "ReceiptId");

            migrationBuilder.AddForeignKey(
                name: "FK_WarrantyRecords_StorageFiles_BackImageId",
                schema: "family",
                table: "WarrantyRecords",
                column: "BackImageId",
                principalSchema: "ais",
                principalTable: "StorageFiles",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_WarrantyRecords_StorageFiles_FrontImageId",
                schema: "family",
                table: "WarrantyRecords",
                column: "FrontImageId",
                principalSchema: "ais",
                principalTable: "StorageFiles",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_WarrantyRecords_StorageFiles_ReceiptId",
                schema: "family",
                table: "WarrantyRecords",
                column: "ReceiptId",
                principalSchema: "ais",
                principalTable: "StorageFiles",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_WarrantyRecords_StorageFiles_BackImageId",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.DropForeignKey(
                name: "FK_WarrantyRecords_StorageFiles_FrontImageId",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.DropForeignKey(
                name: "FK_WarrantyRecords_StorageFiles_ReceiptId",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.DropTable(
                name: "StorageFiles",
                schema: "ais");

            migrationBuilder.DropIndex(
                name: "IX_WarrantyRecords_BackImageId",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.DropIndex(
                name: "IX_WarrantyRecords_FrontImageId",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.DropIndex(
                name: "IX_WarrantyRecords_ReceiptId",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.DropColumn(
                name: "BackImageId",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.DropColumn(
                name: "FrontImageId",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.DropColumn(
                name: "ReceiptId",
                schema: "family",
                table: "WarrantyRecords");

            migrationBuilder.AddColumn<string>(
                name: "BackImage",
                schema: "family",
                table: "WarrantyRecords",
                type: "nvarchar(1024)",
                maxLength: 1024,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "FrontImage",
                schema: "family",
                table: "WarrantyRecords",
                type: "nvarchar(1024)",
                maxLength: 1024,
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Receipt",
                schema: "family",
                table: "WarrantyRecords",
                type: "nvarchar(1024)",
                maxLength: 1024,
                nullable: true);
        }
    }
}
